# Usa una imagen base que tenga Node.js preinstalado
FROM node:18

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Copia los archivos de configuración de Webpack
COPY webpack.config.js .

# Copia los archivos de la aplicación al contenedor
COPY ./src .

# Copia los archivos de configuración de npm
COPY package.json .
COPY package-lock.json .

# Instala las dependencias
RUN npm install

# Ejecuta Webpack para construir tu aplicación
RUN npm run build

# Expone el puerto en el que la aplicación se ejecutará dentro del contenedor
EXPOSE 3000

# Comando para ejecutar la aplicación cuando se inicie el contenedor
CMD ["npm", "start"]
